#!/usr/bin/env python
# -*- Mode: python; tab-width: 4; indent-tabs-mode: nil; encoding: utf-8 -*-
"""
bgz
http://github.com/mtvee/bgz
License Mozilla Public License 1.1 (MPL 1.1)
Copyright (c) 2010 J. Knight. All rights reserved.
"""

import os
import sys
import getopt
import UserDict

from bugz.bugz import Bugz

help_message = '''
A simple command line issue tracking tool to keep issues in the file 
system, with the project and in the repository.

bgz [OPTIONS] [COMMAND] [ARGS...]
where OPTIONS are:
  --help            - print this screen

COMMANDS are:  
    bgz help        - for more info
'''

class Usage(Exception):
    def __init__(self, msg):
        self.msg = msg

def main(argv=None):
  
    defaults = UserDict.UserDict()
    defaults.verbose = False
    defaults.debug = False
    
    if argv is None:
        argv = sys.argv
    try:
        try:
            opts, args = getopt.getopt(argv[1:], "dho:v", ["debug","help", "output=","verbose"])
        except getopt.error, msg:
            raise Usage(msg)


        # option processing
        for option, value in opts:
            if option in ("-v","--verbose"):
                defaults.verbose = True
            if option in ("-d","--debug"):
                defaults.debug = True
            if option in ("-h", "--help"):
                raise Usage(help_message)
            if option in ("-o", "--output"):
                output = value

        b = Bugz( opts )
        b.run( args )
        
    except Usage, err:
        print >> sys.stderr, sys.argv[0].split("/")[-1] + ": " + str(err.msg)
        return 2

# ---------
# M A I N
# ---------
if __name__ == "__main__":
    sys.exit(main())
