#!/usr/bin/env python
# -*- Mode: python; tab-width: 4; indent-tabs-mode: nil; encoding: utf-8 -*-
"""
bgz
http://github.com/mtvee/bgz
License Mozilla Public License 1.1 (MPL 1.1)
Copyright (c) 2010 J. Knight. All rights reserved.
"""

import os
import sys
import getopt
import UserDict

import bugz        
from bugz.bugz import Bugz

help_message = '''
A simple command line issue tracking tool to keep issues in the file 
system, with the project and in the repository.

bgz [OPTIONS] [COMMAND] [ARGS...]
where OPTIONS are:
  -d,--debug
  -h,--help            - print this screen
  -q,--quiet
  -v,--verbose
  -V,--version

COMMANDS are:  
    bgz help        - for more info
'''

class Usage(Exception):
    def __init__(self, msg):
        self.msg = os.path.basename(sys.argv[0]) + " v" + bugz.__version__ 
        self.msg = self.msg + bugz.__copyright__ + ' ' + bugz.__author__
        self.msg = self.msg + "\n" + msg

def main(argv=None):
    
    # default command line options
    options = UserDict.UserDict()
    options.verbose = True
    options.debug = False
    options.ansi = True
    
    if argv is None:
        argv = sys.argv
    try:
        try:
            opts, args = getopt.getopt(argv[1:], "dho:vVq", ["debug","help", "output=","verbose","version","quiet"])
        except getopt.error, msg:
            raise Usage(msg)


        # option processing
        for option, value in opts:
            if option in ("-v","--verbose"):
                options.verbose = True
            if option in ("-q","--quiet"):
                options.verbose = False
            if option in ("-d","--debug"):
                options.debug = True
            if option in ("-h", "--help"):
                raise Usage(help_message)
            if option in ("-o", "--output"):
                output = value
            if option in ("-V", "--version"):
                print os.path.basename(sys.argv[0]) + " v" + bugz.__version__,
                print bugz.__copyright__ + ' ' + bugz.__author__
                print bugz.__url__
                sys.exit( 0 )

                
        b = Bugz( options )
        b.run( args )
        
    except Usage, err:
        print >> sys.stderr, sys.argv[0].split("/")[-1] + ": " + str(err.msg)
        return 2

# ---------
# M A I N
# ---------
if __name__ == "__main__":
    sys.exit(main())
